### ISSUE TITLE
Boolean is not supported 

### ISSUE THREAD

**Issue by PMX** [SAP/python-pyodata#106]
CalculatePoEScore c4codata.SellingPointValuation TypeInfo(namespace='c4codata', name='SellingPointValuation', is_collection=False)
CalculateScore c4codata.StoreValuation TypeInfo(namespace='c4codata', name='StoreValuation', is_collection=False)
CheckAppointmentByGroupwareID Collection(c4codata.Boolean) TypeInfo(namespace='c4codata', name='Boolean', is_collection=True)
Traceback (most recent call last):
  File "C:/dev/PyOdataTest/pyodata_test.py", line 19, in <module>
    my_service = pyodata.Client(SERVICE_URL, session)
  File "C:\dev\python-pyodata\pyodata\client.py", line 68, in __new__
    schema = pyodata.v2.model.MetadataBuilder(metadata, config=config).build()
  File "C:\dev\python-pyodata\pyodata\v2\model.py", line 2499, in build
    schema = Schema.from_etree(edm_schemas, self._config)
  File "C:\dev\python-pyodata\pyodata\v2\model.py", line 1139, in from_etree
    efn.return_type = schema.get_type(efn.return_type_info)
  File "C:\dev\python-pyodata\pyodata\v2\model.py", line 878, in get_type
    raise PyODataModelError(
pyodata.exceptions.PyODataModelError: Neither primitive types nor types parsed from service metadata contain requested type Boolean

**Comment by phanak-sap** [comment]
Since Edm.Boolean is V4 only and no update of the issue for a long time, I would consider this as duplicate for enhancement #39
