### ISSUE TITLE
Is Pyodata compatible with OData V4

### ISSUE THREAD

**Issue by charcpg16** [SAP/python-pyodata#217]
Hi,
  I see that Pyodata is compatible with OData V2. Just want to check if it compatible with OData V4. I am able to connect but not able to query. 
  I get the below error for the line execute():
  Traceback (most recent call last):
  File "c:\V\simple_OData_get_data.py", line 21, in <module>
    **for pending_hire in theservice.entity_sets.PENDING_HIRES.get_entities().execute():**
  File "C:\Users\v\AppData\Local\Programs\Python\Python310\lib\site-packages\pyodata\v2\service.py", line 332, in execute
    return self._handler(response)
  File "C:\Users\v\AppData\Local\Programs\Python\Python310\lib\site-packages\pyodata\v2\service.py", line 1438, in get_entities_handler
    entities = content['d']
KeyError: 'd'

**Comment by phanak-sap** [comment]
Not at the moment. Just odata v2. It is the plan. The issue #39 tracks it - although the work needs to re-start.
