### ISSUE TITLE
'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by wesselvrij** [SAP/python-pyodata#84]
Hi,

I'm trying to make a connection to the Reporting API from Topdesk, but it doesn't seem to work.

OS: Windows 10 Pro
Python:  3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)]

certifi | 2019.11.28 | 2019.11.28
chardet | 3.0.4 | 3.0.4
idna | 2.9 | 2.9
lxml | 4.5.0 | 4.5.0
pip | 19.2.3 | 20.0.2
pyodata | 1.3.0 | 1.3.0
requests | 2.23.0 | 2.23.0
setuptools | 41.2.0 | 45.2.0
urllib3 | 1.25.8 | 1.25.8

**Code:**

import pyodata
import requests

url = 'https://<topdesk-installation>.topdesk.net/services/reporting/v2/odata/'
session = requests.Session()
session.auth = ('<username>','<password>')

client = pyodata.Client(url, session)

**Expected:**

A new client object

**Result:**
Traceback (most recent call last):
  File "C:/Users/<my-folder-structure>/first.py", line 8, in <module>
    client = pyodata.Client(url, session)
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\client.py", line 59, in __new__
    schema = pyodata.v2.model.MetadataBuilder(resp.content, config=config).build()
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 2460, in build
    schema = Schema.from_etree(edm_schemas, self._config)
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 991, in from_etree
    config.err_policy(ParserError.ENTITY_TYPE).resolve(ex)
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 59, in resolve
    raise ekseption
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 989, in from_etree
    etype = EntityType.from_etree(entity_type, config)
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 1388, in from_etree
    navp = NavigationTypeProperty.from_etree(proprty)
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 1705, in from_etree
    node.get('Name'), node.get('FromRole'), node.get('ToRole'), Identifier.parse(node.get('Relationship')))
  File "C:\Users\<my-user>\AppData\Local\Programs\Python\Python38-32\lib\site-packages\pyodata\v2\model.py", line 156, in parse
    parts = value.split('.')
AttributeError: 'NoneType' object has no attribute 'split'

Note: I'm using PyCharm without any virtual environment

As I think you will understand, I've had to replace some things. As a result you will not be able to reproduce my situation, but I still hope you'll be able to find out if I'm doing something wrong or if there is any bug in the library.

Thank you!

**Comment by filak-sap** [comment]
@wesselvrij  Thank you for taking the time to report this issue. Unfortunately, I cannot fix the problem because I have to see the part of $metadata which we failed to parse.

pyodata expects that NavigationProperty definitions to have the attribute Relationship set to an EntityType name. In your case, the attribute was not set at all and I am not sure why.

You can see the expected NavigationProperty definition at:
https://github.com/SAP/python-pyodata/blob/master/tests/metadata.xml#L88

Could you please analyze NavigationProperty definitions in your $metadata and post the excerpt we failed to parse here?

This is URL template:
`https://.topdesk.net/services/reporting/v2/odata/$metadata`

**Comment by wesselvrij** [comment]
@filak-sap 

Thank you for your response.

I'm pretty new to this, so I don't know how to analyze $metadata. Can you tell me how I can open this? I've looked for some tools, but wasn't able to find a suitable one.

**Comment by filak-sap** [comment]
It should be an XML document [0], you can open it your favorite text editor (I bet you can use pycharm).

0: https://www.odata.org/blog/queryable-odata-metadata/

**Comment by wesselvrij** [comment]
I think didn't state my question properly. I'm sorry. My actual question was how to get this document?

**Comment by developer992** [comment]
I have the same problem and odata v4 

how is this XML defined, is this automatic or is defined manually?

**Comment by developer992** [comment]
wait, this library only works with v2?
