### ISSUE TITLE
requests missing in requirements.txt

### ISSUE THREAD

**Issue by wegenerbenjamin** [SAP/python-pyodata#97]
The mandatory library `requests` is missing in requirements (after installing pyodata over `pip install pyodata`):

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import pyodata
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyodata
  File "C:\Program Files\Python 3.6.5\lib\site-packages\pyodata\__init__.py", line 3, in <module>
    from .client import Client
  File "C:\Program Files\Python 3.6.5\lib\site-packages\pyodata\client.py", line 7, in <module>
    import pyodata.v2.service
  File "C:\Program Files\Python 3.6.5\lib\site-packages\pyodata\v2\service.py", line 17, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by filak-sap** [comment]
@wegenerbenjamin thank you for taking the time to report this isssue. My goal was to have pyodata without the hard dependency on requests and hence I committed https://github.com/SAP/python-pyodata/commit/9902d9430ec400395912e93241d6038f62b72a95
